name: auth_firebase
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.3
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  internet_connection_checker: ^1.0.0+1
  otp_text_field: ^1.1.3

dev_dependencies:

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/logos
