name: auth_firebase
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  get: ^4.6.6
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.9.0
  connectivity_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1
  firebase_auth: ^4.14.1
  google_fonts: ^6.1.0
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
